### ISSUE TITLE
Cannot move to next line in contenteditable div

### ISSUE THREAD

**Issue by CodeWithOz** [TarekRaafat/autoComplete.js#249]
- [x] **System Information**
  - [x] Browser type and version: Chrome webview 91.0.4472.101 on Android
  - [x] OS type and version: Android 8.1.0, using [cordova](https://cordova.apache.org/) 9 and 10
  - [x] Any error messages in the JS console: none

- [x] **Describe the bug**

Using this library for a contenteditable div, pressing the "Enter" key doesn't cause the cursor to move to the next line. Essentially I can't create a new line using the "Enter" key. The correct behavior is that I should be able to create as many new lines as I want without this library preventing that behavior.

- [x] **To Reproduce**
Steps to reproduce the behavior: <!-- Example below-!>
1. Download the APK available [here](https://github.com/CodeWithOz/cordova-bad-web-workers/actions/runs/973079514)
2. After opening the app, type into the text field (green-blue box) and hit the "Enter" key to create a new line. It doesn't work. You can clear all the text you've typed and try creating a new line, it still won't work.

- [x] **Expected behavior**
Pressing the "Enter" key should always create a new line

- [x] **Screenshots or GIF's (optional, but HIGHLY RECOMMENDED)**
Not applicable

- [x] **Additional context (optional)**
This is for a cordova app as described earlier.

**Comment by TarekRaafat** [comment]
Hello @CodeWithOz,

Thank you for reporting your use case.
I've already implemented in the coming version `v10.2` a solution for such use cases.

Cheers, and have a nice day! :)

**Comment by CodeWithOz** [comment]
Awesome work, thanks! When can we expect `v10.2` to be released?

**Comment by TarekRaafat** [comment]
Thanks! `v10.2` will be released early next week.

**Comment by CodeWithOz** [comment]
@TarekRaafat hey it seems the problem isn't fully fixed, now I can only create one newline at a time. If the line I'm on doesn't contain any text, I can't create another new line. Is that expected? If so, can I disable it? Previously I used to be able to create as many newlines as I wanted even if they were all empty.

**Comment by TarekRaafat** [comment]
Hello @CodeWithOz,

Are you using `v10.2.6` with the `submit` API?

**Comment by CodeWithOz** [comment]
No I'm not using it. I don't specify it in my config and from the docs the default is `false`, so that should mean it's disabled.

**Comment by TarekRaafat** [comment]
> No I'm not using it. I don't specify it in my config and from the docs the default is `false`, so that should mean it's disabled.

You need to set `submit` to `true` to enable the default `enter` button behavior, which is disabled by default.

Would you please try it and let me know how it goes?

**Comment by CodeWithOz** [comment]
@TarekRaafat yep that was the fix, thank you!
